services:
  - type: web
    name: automacao-excel
    runtime: node
    region: oregon
    plan: starter
    buildCommand: |
      npm install
      npx playwright install chromium
      npx playwright install-deps
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: 0
